#!/bin/bash
set -e

# Source profile
source ~/.profile

# Run service
sudo docker stack deploy -c /portal/docker-compose.yml portal

# Cleanup unused resources
sudo docker image prune -a -f
sudo docker container prune -f
sudo docker volume prune -f
sudo docker network prune -f
